sudo: false
dist: trusty
language: generic
services: docker

before_script:
    - export IMAGE="dunecommunity/dune-xt-common-testing_${DOCKER_TAG}:${TRAVIS_BRANCH}"
    # get image with fallback to master branch of the super repo
    - docker pull ${IMAGE} || export IMAGE="dunecommunity/dune-xt-common-testing_${DOCKER_TAG}:master" ; docker pull ${IMAGE}
    - export ENV_FILE=${HOME}/env
    - python3 ./.travis.make_env_file.py
    - export MY_MODULE=dune-visibilty-demo
    - export DOCKER_RUN="docker run --env-file ${ENV_FILE} -v ${TRAVIS_BUILD_DIR}:/root/src/dune-xt-common ${IMAGE}"

script:
    - ${DOCKER_RUN} /root/src/dune-xt-common/.travis.script.bash

# runs independent of 'script' failure/success
after_script:
    # output for simpler replicability
    - docker images ${IMAGE}
    - echo ${DOCKER_RUN}


notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis

#after_success:
#- coveralls

branches:
  except:
    - gh-pages

stages:
    - Test

jobs:
  include:
  - stage: Test
    env: DOCKER_TAG=debian_gcc
  - stage: Test
    env: DOCKER_TAG=arch_gcc


#   THIS FILE IS AUTOGENERATED -- DO NOT EDIT  #
#  Re-run .ci/templates/update.py --nd instead #
